### ISSUE TITLE
Customize registry

### ISSUE THREAD

**Issue by terlar** [aakropotkin/floco#42]
Is it possible to customize the registry, e.g. to not use registry.npmjs.org, but instead a custom artifactory registry or similar.

I didn't find this in the docs or the source code.

**Comment by aakropotkin** [comment]
Yeah you definitely can, I use a private registry with it regularly. I
haven't written good docs on it yet though.

I'm about to hop on a plane and will be pretty busy this week so probably
not going to write a guide this week, but if you hop onto the Matrix chat I
can walk you through the set up since that's a bit less effort than writing
a guide.

**Comment by terlar** [comment]
Or perhaps you would like to have it open, until the documentation is in place? Either documentation about the NPM flags or explicitly about custom registry.
